site:
  name: Ехадом
  site: 'https://ehadom.com/'
  base: '/'
  trailingSlash: false

  googleSiteVerificationId: TBD

# Default SEO metadata
metadata:
  title:
    default: Ehadom
    template: '%s — Ehadom'
  description: "\U0001F680 Smart home providers."
  robots:
    index: true
    follow: true
  openGraph:
    site_name: Ehadom
    images:
      - url: '~/assets/images/default.png'
        width: 1200
        height: 628
    type: website
  twitter:
    handle: '@qbaware'
    site: '@qbaware'
    cardType: summary_large_image

analytics:
  vendors:
    googleAnalytics:
      id: null # or "G-XXXXXXXXXX"

ui:
  theme: 'light'
